# cargo-vet configuration for phylax

[cargo-vet]
version = "0.10"

[imports.mozilla]
url = "https://raw.githubusercontent.com/nickel-org/nickel.rs/main/supply-chain/audits.toml"

[policy.phylax]
audit-as-crates-io = false
