#!/usr/bin/env bash
set -euo pipefail

# Run criterion benchmarks and produce two outputs:
#   1) CSV history (appended each run)   — for tracking regressions over time
#   2) Markdown table (overwritten)      — last 3 runs per benchmark for trend tracking
#
# Usage:
#   ./scripts/bench-history.sh                          # defaults (all benches)
#   ./scripts/bench-history.sh results.csv results.md   # custom paths

HISTORY_FILE="${1:-bench-history.csv}"
MD_FILE="${2:-bench-latest.md}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

# Create CSV header if file doesn't exist
if [ ! -f "$HISTORY_FILE" ]; then
    echo "timestamp,commit,branch,benchmark,low_ns,estimate_ns,high_ns" > "$HISTORY_FILE"
fi

echo "Running benchmarks..."
echo "  commit: $COMMIT"
echo "  branch: $BRANCH"
echo ""

# Run all benchmarks and capture output
BENCH_OUTPUT=$(cargo bench 2>&1 | sed 's/\x1b\[[0-9;]*m//g')

# Show full output
echo "$BENCH_OUTPUT"
echo ""

# ── Helper: normalise a value+unit pair to nanoseconds ───────────────────────
to_ns() {
    local val="$1" unit="$2"
    case "$unit" in
        ps)     awk "BEGIN {printf \"%.4f\", $val / 1000}" ;;
        ns)     echo "$val" ;;
        µs|us)  awk "BEGIN {printf \"%.4f\", $val * 1000}" ;;
        ms)     awk "BEGIN {printf \"%.4f\", $val * 1000000}" ;;
        s)      awk "BEGIN {printf \"%.4f\", $val * 1000000000}" ;;
        *)      echo "$val" ;;
    esac
}

# ── Helper: format ns to a human-readable string ────────────────────────────
human_ns() {
    local ns="$1"
    awk "BEGIN {
        v = $ns
        if      (v < 1)           printf \"%.2f ps\", v * 1000
        else if (v < 1000)        printf \"%.2f ns\", v
        else if (v < 1000000)     printf \"%.2f µs\", v / 1000
        else if (v < 1000000000)  printf \"%.2f ms\", v / 1000000
        else                      printf \"%.2f s\",  v / 1000000000
    }"
}

# ── Parse criterion output and append to CSV ─────────────────────────────────
LINES_ADDED=0
PREV_LINE=""

while IFS= read -r line; do
    if [[ "$line" == *"time:"*"["* ]]; then
        # Extract benchmark name
        BENCH_NAME=$(echo "$line" | sed -E 's/[[:space:]]*time:.*//' | xargs)
        if [ -z "$BENCH_NAME" ]; then
            BENCH_NAME=$(echo "$PREV_LINE" | xargs)
        fi

        # Extract the three values inside brackets: [low mid high]
        VALS=$(echo "$line" | sed -E 's/.*\[(.+)\]/\1/')
        LOW_VAL=$(echo "$VALS" | awk '{print $1}')
        LOW_UNIT=$(echo "$VALS" | awk '{print $2}')
        MID_VAL=$(echo "$VALS" | awk '{print $3}')
        MID_UNIT=$(echo "$VALS" | awk '{print $4}')
        HIGH_VAL=$(echo "$VALS" | awk '{print $5}')
        HIGH_UNIT=$(echo "$VALS" | awk '{print $6}')

        LOW_NS=$(to_ns "$LOW_VAL" "$LOW_UNIT")
        MID_NS=$(to_ns "$MID_VAL" "$MID_UNIT")
        HIGH_NS=$(to_ns "$HIGH_VAL" "$HIGH_UNIT")

        # Append to CSV
        echo "${TIMESTAMP},${COMMIT},${BRANCH},${BENCH_NAME},${LOW_NS},${MID_NS},${HIGH_NS}" >> "$HISTORY_FILE"
        LINES_ADDED=$((LINES_ADDED + 1))
    fi
    PREV_LINE="$line"
done <<< "$BENCH_OUTPUT"

# ── Build 3-point tracking markdown from CSV history ─────────────────────────
# Collect the last 3 unique run timestamps
TIMESTAMPS=($(tail -n +2 "$HISTORY_FILE" | awk -F, '{print $1}' | sort -u | tail -3))
NUM_TS=${#TIMESTAMPS[@]}

# Labels for columns (most recent last)
declare -a COL_LABELS=()
for i in $(seq 0 $((NUM_TS - 1))); do
    ts="${TIMESTAMPS[$i]}"
    col_commit=$(grep "^${ts}," "$HISTORY_FILE" | head -1 | awk -F, '{print $2}')
    short_date=$(echo "$ts" | sed 's/T.*//; s/^20//')
    COL_LABELS+=("${short_date} (${col_commit})")
done

# Get ordered list of benchmark names (preserve order from latest run)
LATEST_TS="${TIMESTAMPS[$((NUM_TS - 1))]}"
BENCH_NAMES=($(grep "^${LATEST_TS}," "$HISTORY_FILE" | awk -F, '{print $4}'))

{
    echo "# Benchmark Results — Last ${NUM_TS} Runs"
    echo ""

    # Header row
    HEADER="| Benchmark |"
    SEP="|-----------|"
    for label in "${COL_LABELS[@]}"; do
        HEADER+=" ${label} |"
        SEP+="------|"
    done
    echo "$HEADER"
    echo "$SEP"

    # Data rows
    for bench in "${BENCH_NAMES[@]}"; do
        ROW="| ${bench} |"
        for ts in "${TIMESTAMPS[@]}"; do
            est_ns=$(grep "^${ts},.*,${bench}," "$HISTORY_FILE" | awk -F, '{print $6}' | head -1)
            if [ -n "$est_ns" ]; then
                ROW+=" $(human_ns "$est_ns") |"
            else
                ROW+=" — |"
            fi
        done
        echo "$ROW"
    done

    echo ""
    echo "_Generated by \`scripts/bench-history.sh\` — showing point estimates from last ${NUM_TS} runs_"
} > "$MD_FILE"

echo ""
echo "Appended ${LINES_ADDED} benchmark entries to ${HISTORY_FILE}"
echo "Latest results written to ${MD_FILE} (${NUM_TS}-point tracking)"
