#!/usr/bin/env bash
set -euo pipefail

# Run Cyrius benchmarks and produce two outputs:
#   1) CSV history (appended each run)   — for tracking regressions over time
#   2) Markdown table (overwritten)      — last 3 runs per benchmark for trend tracking
#
# Usage:
#   ./scripts/bench-history.sh                          # defaults (all benches)
#   ./scripts/bench-history.sh results.csv results.md   # custom paths

HISTORY_FILE="${1:-bench-history.csv}"
MD_FILE="${2:-bench-latest.md}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

# Create CSV header if file doesn't exist
if [ ! -f "$HISTORY_FILE" ]; then
    echo "timestamp,commit,branch,benchmark,iterations,total_ns,per_iter_ns" > "$HISTORY_FILE"
fi

echo "Running benchmarks..."
echo "  commit: $COMMIT"
echo "  branch: $BRANCH"
echo ""

# Build and run benchmarks
cyrius build tests/phylax.bcyr build/phylax-bench 2>&1
BENCH_OUTPUT=$(./build/phylax-bench 2>&1 || true)

# Show full output
echo "$BENCH_OUTPUT"
echo ""

# ── Helper: format ns to a human-readable string ────────────────────────────
human_ns() {
    local ns="$1"
    awk "BEGIN {
        v = $ns
        if      (v < 1)           printf \"%.2f ps\", v * 1000
        else if (v < 1000)        printf \"%.2f ns\", v
        else if (v < 1000000)     printf \"%.2f µs\", v / 1000
        else if (v < 1000000000)  printf \"%.2f ms\", v / 1000000
        else                      printf \"%.2f s\",  v / 1000000000
    }"
}

# ── Parse bench output and append to CSV ─────────────────────────────────
# Expected format from Cyrius bench: "name: Niters total_ns ns/iter per_iter_ns"
LINES_ADDED=0

while IFS= read -r line; do
    # Match lines like: "entropy_1k: 10000 iters, 1234567 ns total, 123 ns/iter"
    if [[ "$line" == *"iters"*"ns"* ]]; then
        BENCH_NAME=$(echo "$line" | sed -E 's/:.*//' | xargs)
        ITERS=$(echo "$line" | grep -oP '\d+(?= iters)' || echo "0")
        TOTAL_NS=$(echo "$line" | grep -oP '\d+(?= ns total)' || echo "0")
        PER_ITER=$(echo "$line" | grep -oP '\d+(?= ns/iter)' || echo "0")

        if [ -n "$BENCH_NAME" ] && [ "$ITERS" != "0" ]; then
            echo "${TIMESTAMP},${COMMIT},${BRANCH},${BENCH_NAME},${ITERS},${TOTAL_NS},${PER_ITER}" >> "$HISTORY_FILE"
            LINES_ADDED=$((LINES_ADDED + 1))
        fi
    fi
done <<< "$BENCH_OUTPUT"

# ── Build 3-point tracking markdown from CSV history ─────────────────────
TIMESTAMPS=($(tail -n +2 "$HISTORY_FILE" | awk -F, '{print $1}' | sort -u | tail -3))
NUM_TS=${#TIMESTAMPS[@]}

if [ "$NUM_TS" -eq 0 ]; then
    echo "No benchmark data found in $HISTORY_FILE"
    exit 0
fi

# Labels for columns
declare -a COL_LABELS=()
for i in $(seq 0 $((NUM_TS - 1))); do
    ts="${TIMESTAMPS[$i]}"
    col_commit=$(grep "^${ts}," "$HISTORY_FILE" | head -1 | awk -F, '{print $2}')
    short_date=$(echo "$ts" | sed 's/T.*//; s/^20//')
    COL_LABELS+=("${short_date} (${col_commit})")
done

# Get ordered list of benchmark names from latest run
LATEST_TS="${TIMESTAMPS[$((NUM_TS - 1))]}"
BENCH_NAMES=($(grep "^${LATEST_TS}," "$HISTORY_FILE" | awk -F, '{print $4}'))

{
    echo "# Benchmark Results — Last ${NUM_TS} Runs"
    echo ""

    HEADER="| Benchmark |"
    SEP="|-----------|"
    for label in "${COL_LABELS[@]}"; do
        HEADER+=" ${label} |"
        SEP+="------|"
    done
    echo "$HEADER"
    echo "$SEP"

    for bench in "${BENCH_NAMES[@]}"; do
        ROW="| ${bench} |"
        for ts in "${TIMESTAMPS[@]}"; do
            per_iter=$(grep "^${ts},.*,${bench}," "$HISTORY_FILE" | awk -F, '{print $7}' | head -1)
            if [ -n "$per_iter" ]; then
                ROW+=" $(human_ns "$per_iter") |"
            else
                ROW+=" — |"
            fi
        done
        echo "$ROW"
    done

    echo ""
    echo "_Generated by \`scripts/bench-history.sh\` — showing per-iteration times from last ${NUM_TS} runs_"
} > "$MD_FILE"

echo ""
echo "Appended ${LINES_ADDED} benchmark entries to ${HISTORY_FILE}"
echo "Latest results written to ${MD_FILE} (${NUM_TS}-point tracking)"
